# slack
slack_host = "https://<your-slack-team>.slack.com"
slack_token = "<your-token>"

# etc
jira_host = "https://<your-jira>.atlassian.net"
jira_email = "<your-jira-email>"
jira_token = "<your-jira-token>"
